name: Metrics
on:
  schedule: [{ cron: "0 */12 * * *" }] # updates every 12 hours
  workflow_dispatch: # allows manual trigger
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: chakra121
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Kolkata
          plugin_languages: yes
          plugin_stars: yes
          plugin_habits: yes
